/*
 * Copyright 2026 Humaid Alqasimi
 * SPDX-License-Identifier: Apache-2.0
 */
package db

import "errors"

var (
	ErrDatabaseConnectionNotInitialized = errors.New("database connection not initialized")
	ErrDatabaseURLEnvVarNotSet          = errors.New("DATABASE_URL environment variable is not set")
	ErrDatabaseNameNotSpecified         = errors.New("no database name specified in DATABASE_URL")
	ErrDisplayNameRequired              = errors.New("display name is required")
	ErrUsernameRequired                 = errors.New("username is required")
	ErrInvalidUsername                  = errors.New("username must be 3-32 characters and use only lowercase letters, numbers, dots, dashes, or underscores")
	ErrUsernameTaken                    = errors.New("username is already in use")
	ErrPasswordRequired                 = errors.New("password is required")
	ErrPasswordTooShort                 = errors.New("password must be at least 8 characters")
	ErrInvalidUsernameOrPassword        = errors.New("invalid username or password")
	ErrInvalidRole                      = errors.New("invalid role")
	ErrUserNotFound                     = errors.New("user not found")
	ErrUserDeactivated                  = errors.New("user is deactivated")
	ErrUserAlreadyDeactivated           = errors.New("user is already deactivated")
	ErrCannotDeactivateCurrentUser      = errors.New("you cannot deactivate your own account")
	ErrActiveAdminRequired              = errors.New("at least one active admin account is required")
	ErrInvalidUserHandle                = errors.New("invalid user handle")
	ErrPasskeyNotFound                  = errors.New("passkey not found")
	ErrSetupAlreadyCompleted            = errors.New("setup already completed")
	ErrInviteInvalidOrUsed              = errors.New("invite is no longer valid")
	ErrInvalidCreatorID                 = errors.New("invalid creator ID")
	ErrInviteNotFound                   = errors.New("invite not found")
	ErrInviteNotExpired                 = errors.New("invite is not expired")
	ErrAccessDenied                     = errors.New("access denied")
	ErrAdminRequired                    = errors.New("admin required")
	ErrTeacherRequired                  = errors.New("teacher required")
	ErrStudentRequired                  = errors.New("student required")
	ErrCourseCodeRequired               = errors.New("course code is required")
	ErrCourseTitleRequired              = errors.New("course title is required")
	ErrCourseTermRequired               = errors.New("course term is required")
	ErrCourseNotFound                   = errors.New("course not found")
	ErrCourseAlreadyExists              = errors.New("course already exists for this term")
	ErrCourseUnitTitleRequired          = errors.New("unit title is required")
	ErrCourseUnitNotFound               = errors.New("unit not found")
	ErrUnitLessonTitleRequired          = errors.New("lesson title is required")
	ErrUnitLessonNotFound               = errors.New("lesson not found")
	ErrLessonSlideMarkdownRequired      = errors.New("slide markdown is required")
	ErrLessonSlideNotFound              = errors.New("slide not found")
	ErrOutlineItemNotFound              = errors.New("outline item not found")
	ErrCourseInstructorAlreadyAssigned  = errors.New("teacher is already assigned to this course")
	ErrCourseStudentAlreadyEnrolled     = errors.New("student is already enrolled in this course")
	ErrAssignmentTitleRequired          = errors.New("assignment title is required")
	ErrAssignmentMaxGradeRequired       = errors.New("assignment max grade is required")
	ErrAssignmentMaxGradeInvalid        = errors.New("assignment max grade must be a non-negative number")
	ErrAssignmentNotFound               = errors.New("assignment not found")
	ErrSubmissionNotFound               = errors.New("submission not found")
	ErrSubmissionFileRequired           = errors.New("submission file is required")
	ErrSubmissionFileNameRequired       = errors.New("submission file name is required")
	ErrSubmissionFileTooLarge           = errors.New("submission file is too large")
	ErrSubmissionPastDue                = errors.New("assignment is past due")
	ErrGradeValueRequired               = errors.New("grade value is required")
	ErrGradeValueInvalid                = errors.New("grade value must be a non-negative number")
	ErrGradeExceedsAssignmentMaximum    = errors.New("grade value exceeds the assignment maximum")
	ErrGradeNotFound                    = errors.New("grade not found")
	ErrCourseCompletionRequired         = errors.New("course completion is required before issuing a certificate")
	ErrCourseAlreadyCertified           = errors.New("an active certificate already exists for this student in this course")
	ErrCertificateNotFound              = errors.New("certificate not found")
	ErrBlockchainAlreadyInitialized     = errors.New("blockchain already initialized")
	ErrBlockchainEventTypeRequired      = errors.New("blockchain event type is required")
	ErrBlockchainEntityTypeRequired     = errors.New("blockchain entity type is required")
	ErrInvalidBlockchainActorUserID     = errors.New("invalid blockchain actor user id")

	ErrInvalidPostgresSessionIniterArgument = errors.New("invalid PostgresSessionIniter argument")
)
